# Generated by Django 5.2.5 on 2026-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0004_user_transaction_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
