# Generated by Django 5.2.5 on 2026-04-22 08:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0005_user_pin_failed_attempts_user_pin_locked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                default=1,
                help_text="Mobile number is the primary login identifier.",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (e.g. +919876543210).",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="kyc",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_ID", "National ID Card"),
                    ("DRIVERS_LICENSE", "Driver's License"),
                    ("PASSPORT", "International Passport"),
                    ("AADHAAR", "Aadhaar Card"),
                    ("PAN", "PAN Card"),
                ],
                default="AADHAAR",
                max_length=28,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="OTPRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("REGISTER", "Register"),
                            ("BANK_VERIFY", "Bank Account Verification"),
                        ],
                        default="LOGIN",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mobile_number", "purpose", "is_used"],
                        name="userauths_o_mobile__557c09_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("SBI", "State Bank of India"),
                            ("HDFC", "HDFC Bank"),
                            ("ICICI", "ICICI Bank"),
                            ("AXIS", "Axis Bank"),
                            ("KOTAK", "Kotak Mahindra Bank"),
                            ("YES", "Yes Bank"),
                            ("PNB", "Punjab National Bank"),
                            ("BOB", "Bank of Baroda"),
                            ("CANARA", "Canara Bank"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(max_length=18)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("account_holder_name", models.CharField(max_length=255)),
                ("registered_mobile", models.CharField(max_length=15)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("FAILED", "Verification Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "verification_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "account_number")},
            },
        ),
    ]
