# Generated by Django 4.2.7 on 2026-04-24 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0006_user_mobile_number_alter_kyc_id_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("PHONE_VERIFY", "Phone Verification"),
                            ("LOGIN", "Login"),
                            ("TRANSACTION", "Transaction Auth"),
                        ],
                        default="PHONE_VERIFY",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="user",
        ),
        migrations.DeleteModel(
            name="OTPRecord",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pin_failed_attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pin_locked_until",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_ID", "National ID Card"),
                    ("DRIVERS_LICENSE", "Driver's License"),
                    ("PASSPORT", "International Passport"),
                ],
                default="NATIONAL_ID",
                max_length=28,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="BankAccount",
        ),
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
