# Generated by Django 4.2.7 on 2026-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0007_otp_alter_bankaccount_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("code", models.CharField(max_length=6)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("PHONE_VERIFY", "Phone Verification"),
                    ("LOGIN", "Login"),
                    ("TRANSACTION", "Transaction Auth"),
                ],
                default="LOGIN",
                max_length=20,
            ),
        ),
    ]
