# Generated by Django 4.2.7 on 2026-04-25 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0008_pendingotp_alter_otp_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("SBI", "State Bank of India"),
                            ("HDFC", "HDFC Bank"),
                            ("ICICI", "ICICI Bank"),
                            ("AXIS", "Axis Bank"),
                            ("KOTAK", "Kotak Mahindra Bank"),
                            ("YES", "Yes Bank"),
                            ("PNB", "Punjab National Bank"),
                            ("BOB", "Bank of Baroda"),
                            ("CANARA", "Canara Bank"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(max_length=18)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("account_holder_name", models.CharField(max_length=255)),
                ("registered_mobile", models.CharField(max_length=15)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("FAILED", "Verification Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "verification_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "account_number")},
            },
        ),
    ]
