# Generated by Django 4.2.7 on 2026-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0009_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="delivery_method",
            field=models.CharField(
                choices=[("SMS", "SMS"), ("EMAIL", "Email"), ("BOTH", "Both")],
                default="SMS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pendingotp",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="pendingotp",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
