# Generated by Django 5.2.5 on 2026-04-21 07:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_savingsgoal_uuid_loan_emipayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="status",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("TRANSFER", "Transfer"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("SAVINGS", "Savings"),
                    ("LOAN", "Loan"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="external_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
