# Generated by Django 4.2.7 on 2026-04-25 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_notification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("TRANSFER", "Transfer"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("SAVINGS", "Savings"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="external_reference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=12),
        ),
    ]
